// products.js
export const products = [
    {
      id: 1,
      name: "Gray Work Pants",
      price: 30,
      image: "ntedja/assets/pants.jpg",
      description: "Gray work pants for women are a versatile and professional wardrobe essential, offering a balance of style, comfort, and functionality. These pants typically come in a variety of fits, including slim, straight-leg, wide-leg, and tapered designs, catering to different body types and preferences.",
      color: "Gray",
      sizes: ["S", "M", "L"],
      type: "Pants",
    },
    {
      id: 2,
      name: "Men's short sleeve striped shirt",
      price: 28,
      image: "ntedja/assets/BajuPria.jpg",
      description: "A men's brown short-sleeve white striped shirt is a stylish and versatile piece that blends a classic and modern aesthetic. Typically made from lightweight materials like cotton, linen, or a cotton-blend, this shirt ensures breathability and comfort, making it ideal for warm weather or casual occasions.",
      color: "Brown",
      sizes: ["S", "M", "L"],
      type: "Men",
    },
    {
      id: 3,
      name: "Men's short sleeve shirt brown",
      price: 25,
      image: "ntedja/assets/BajuPria3.jpg",
      description: "A men's dark brown short-sleeve shirt is a versatile and stylish piece that works well for both casual and semi-formal occasions. Made from breathable fabrics like cotton, linen, or polyester blends, it provides comfort and ease of movement, making it perfect for warm weather.",
      color: "Dark Brown",
      sizes: ["S", "M", "L"],
      type: "Men",
    },
    {
      id: 4,
      name: "Men's short sleeve shirt green",
      price: 25,
      image: "ntedja/assets/BajuPria4.jpg",
      description: "A men's green short-sleeve shirt is a stylish and versatile wardrobe essential that suits a variety of occasions, from casual outings to smart-casual events. Available in shades ranging from olive and forest green to pastel and emerald, this shirt can be tailored to different personal styles and seasons.",
      color: "Dark Green",
      sizes: ["S", "M", "L"],
      type: "Men",
    },
    {
      id: 5,
      name: "Men's short sleeve shirt white",
      price: 25,
      image: "ntedja/assets/BajuPria5.jpg",
      description: "A men's white short-sleeve shirt is a classic and versatile piece that works for various occasions, from casual outings to semi-formal events. Made from breathable fabrics like cotton, linen, or cotton blends, it provides comfort and a lightweight feel, perfect for warm weather.",
      color: "Broken White",
      sizes: ["S", "M", "L"],
      type: "Men",
    },
    {
      id: 6,
      name: "Womens's polo knit",
      price: 20,
      image: "ntedja/assets/BajuPerempuan.jpg",
      description: "This women's polo knit shirt is a stylish and sophisticated piece, featuring a soft knit fabric with a ribbed texture that runs vertically across the garment. The shirt is primarily off-white or cream in color, creating a classic and versatile look.",
      color: "White-Red",
      sizes: ["S", "M", "L"],
      type: "Women",
    },
    {
      id: 7,
      name: "Womens's polo",
      price: 22,
      image: "ntedja/assets/BajuPerempuan2.jpg",
      description: "A women's dark green polo shirt is a versatile and stylish wardrobe essential that blends casual comfort with a polished look. Typically made from breathable fabrics such as cotton, pique knit, or a cotton-polyester blend, it offers softness, durability, and ease of movement.",
      color: "Dark Green-White",
      sizes: ["S", "M", "L"],
      type: "Women",
    },
    {
      id: 8,
      name: "Gray Womens's polo knit",
      price: 20,
      image: "ntedja/assets/BajuPerempuan3.jpg",
      description: "A women's gray polo knit shirt is a sophisticated and versatile wardrobe staple, perfect for both casual and semi-formal settings. Made from a soft knit fabric, it offers a comfortable and slightly stretchy fit, ideal for all-day wear. The ribbed or smooth texture adds subtle detail, enhancing its refined look.",
      color: "Gray",
      sizes: ["S", "M", "L"],
      type: "Women",
    },
    {
      id: 9,
      name: "Brown Jacket",
      price: 40,
      image: "ntedja/assets/Jacket.jpg",
      description: "This is a brown zip-up jacket with a structured and stylish design. It features a classic collar, a full-length silver zipper, and multiple pockets for functionality. The jacket has a cropped or fitted cut, giving it a modern and tailored look.",
      color: "Brown",
      sizes: ["S", "M", "L"],
      type: "Jackets",
    },
    {
      id: 10,
      name: "Light Brown Jacket",
      price: 45,
      image: "ntedja/assets/Jacket1.jpg",
      description: "A light brown jacket is a stylish and versatile outerwear piece that works for both casual and semi-formal occasions. It typically comes in materials such as cotton, wool, suede, or synthetic blends, offering comfort and durability.",
      color: "Light Brown",
      sizes: ["S", "M", "L"],
      type: "Jackets",
    },
    {
      id: 11,
      name: "Brown Bomber Jacket",
      price: 35,
      image: "ntedja/assets/Jacket2.jpg",
      description: "A brown bomber jacket is a classic and versatile outerwear piece known for its stylish and functional design. Originally inspired by military flight jackets, it has evolved into a fashion staple suitable for both casual and smart-casual looks.",
      color: "Brown",
      sizes: ["S", "M", "L"],
      type: "Jackets",
    },
    {
      id: 12,
      name: "Jeans Jacket",
      price: 35,
      image: "ntedja/assets/Jeans.jpg",
      description: "A jean jacket, also known as a denim jacket, is a timeless and versatile outerwear piece that complements a wide range of styles. Originally introduced as durable workwear, it has become a fashion staple for casual and streetwear outfits.",
      color: "Blue Jeans",
      sizes: ["S", "M", "L"],
      type: "Jeans",
    },
    {
      id: 13,
      name: "Red Shirt",
      price: 10,
      image: "ntedja/assets/shirt.jpg",
      description: "A red shirt is a bold and stylish wardrobe essential that adds a pop of color and confidence to any outfit. Available in various materials, fits, and styles, it can be worn for both casual and formal occasions.",
      color: "Red",
      sizes: ["S", "M", "L"],
      type: "T-Shirts",
    },
    {
      id: 14,
      name: "Brown Worker Pants",
      price: 35,
      image: "ntedja/assets/pants2.jpg",
      description: "Brown worker pants are durable and functional trousers designed for both work and casual wear. They are known for their rugged construction, comfortable fit, and utility-focused design, making them a staple for outdoor activities, labor-intensive jobs, and street-style fashion.",
      color: "Light Brown",
      sizes: ["S", "M", "L"],
      type: "Pants",
    },
    {
      id: 15,
      name: "Black Wide-Leg Pants",
      price: 35,
      image: "ntedja/assets/pants6.jpg",
      description: "These are black wide-leg trousers with a folded waistband detail. The pants have a sleek, tailored look with a flared cut, creating a stylish and modern silhouette. The standout feature is the contrast waistband, which appears folded over and features branding or text, adding a unique and edgy touch.",
      color: "Balck-White",
      sizes: ["S", "M", "L"],
      type: "Pants",
    },
    {
      id: 16,
      name: "Black Wide-Leg Pants",
      price: 35,
      image: "ntedja/assets/pants8.jpg",
      description: "These are beige high-waisted flared trousers with pleated slit details. They have a sophisticated and unique design, making them a stylish choice for modern fashion lovers.",
      color: "Beige",
      sizes: ["S", "M", "L"],
      type: "Pants",
    },
    {
      id: 17,
      name: "Beige Shoes",
      price: 105,
      image: "ntedja/assets/shoes.jpg",
      description: "These beige eco-friendly sneakers feature a textured woven fabric upper, giving them a natural and minimalist look. Designed with sustainability in mind, they likely incorporate recycled or organic materials. The classic lace-up design ensures a secure fit, while the durable rubber sole provides comfort and support. Their neutral tone makes them versatile and easy to pair with various outfits, perfect for casual and eco-conscious fashion.",
      color: "Beige",
      sizes: ["S", "M", "L"],
      type: "Shoes",
    },
    {
      id: 18,
      name: "White Boots",
      price: 125,
      image: "ntedja/assets/shoes2.jpg",
      description: "These off-white suede desert boots feature a minimalist and timeless design. They have a soft upper with subtle branding on the side, complemented by a classic lace-up closure. The boots sit on a durable crepe sole, offering comfort and flexibility for everyday wear. Their neutral tone makes them versatile, perfect for casual or semi-formal outfits.",
      color: "White",
      sizes: ["S", "M", "L"],
      type: "Shoes",
    },
    {
      id: 19,
      name: "Pink Floral Ruched Midi Dress Floral Dress",
      price: 30,
      image: "ntedja/assets/dresses1.jpg",
      description: "Turn heads with this stunning pink floral midi dress, designed to flatter your figure with a chic and sophisticated touch. Featuring a structured bustier bodice with a sweetheart neckline and thick shoulder straps, this dress offers a corset-like fit for a sculpted silhouette.",
      color: "Pink",
      sizes: ["S", "M", "L"],
      type: "Dresses",
    },
    {
      id: 20,
      name: "Olive Striped Bustier Maxi Dress",
      price: 33,
      image: "ntedja/assets/dresses2.jpg",
      description: "Make a statement with this effortlessly chic olive striped maxi dress. Designed with a structured bustier-style bodice and a flattering sweetheart neckline, this dress provides a perfect balance of elegance and comfort. The vertical white stripes create a slimming and elongating effect, while the fitted waistline flows into a full, pleated skirt for graceful movement.",
      color: "Olive Green",
      sizes: ["S", "M", "L"],
      type: "Dresses",
    },
    {
      id: 21,
      name: "Elegant Textured Green A-Line Dress",
      price: 31,
      image: "ntedja/assets/dresses3.jpg",
      description: "Make a bold yet sophisticated statement with this stunning green A-line dress. Designed with a structured silhouette, it features a fitted bodice that gracefully flares into a pleated skirt, creating a flattering and timeless shape. The textured fabric adds depth and dimension, giving it a unique and luxurious feel. A subtle front slit neckline and short sleeves enhance its classic yet modern appeal. Perfect for formal events, work settings, or special occasions, this dress can be paired with heels and minimal accessories for a refined and polished look.",
      color: "Green",
      sizes: ["S", "M", "L"],
      type: "Dresses",
    },
    {
      id: 22,
      name: "Floral Embroidered Sleeveless Maxi Dress",
      price: 35,
      image: "ntedja/assets/dresses4.jpg",
      description: "Elevate your elegance with this breathtaking floral embroidered maxi dress. Designed with a delicate sheer overlay, this dress features intricate floral and butterfly embroidery that creates a whimsical and feminine aesthetic. The fitted bodice transitions into a flowing A-line skirt, offering graceful movement and a flattering silhouette. A concealed back zipper ensures a seamless fit, while the sleeveless design makes it perfect for warm-weather occasions.",
      color: "Beige",
      sizes: ["S", "M", "L"],
      type: "Dresses",
    },
    {
      id: 23,
      name: "Elegant Gold & Blue Gemstone Bracelet Watch",
      price: 300,
      image: "ntedja/assets/acc1.jpg",
      description: "Add a touch of sophistication to your wrist with this stunning gold-tone bracelet watch, beautifully adorned with blue and white gemstones. The unique cushion-shaped dial features a minimalistic design with gold-tone hands and markers, set against a classic white face for effortless readability. The bracelet-style band, embellished with carefully arranged gemstones, offers an elegant yet artistic appeal, making this timepiece a standout accessory for any occasion.",
      color: "Gold - Blue",
      sizes: ["One Size"],
      type: "Accessories",
    },
    {
      id: 24,
      name: "Gold Charm Pendant Necklace",
      price: 600,
      image: "ntedja/assets/acc2.jpg",
      description: "This exquisite gold-tone charm necklace is a delicate yet sophisticated piece that brings nature’s beauty to your everyday look. Featuring a trio of carefully curated charms—a lustrous freshwater pearl, a finely detailed gold seashell, and a soft green gemstone pendant—this necklace embodies timeless elegance with a touch of coastal inspiration.",
      color: "Gold",
      sizes: ["One Size"],
      type: "Accessories",
    },
    {
      id: 25,
      name: "Celestial Gold Band Ring - Reach for the Stars",
      price: 400,
      image: "ntedja/assets/acc3.jpg",
      description: "A delicate yet powerful reminder to dream big and shine bright, this celestial-inspired gold band ring is adorned with intricate star engravings and shimmering crystals. Inside, an engraved message—REACH FOR THE STARS—adds a meaningful touch, making it a perfect piece for those who embrace ambition and positivity.",
      color: "Gold",
      sizes: ["One Size"],
      type: "Accessories",
    },
    {
      id: 26,
      name: "Celestial Gold Charm Bracelet - A Cosmic Elegance",
      price: 450,
      image: "ntedja/assets/acc5.jpg",
      description: "A stunning gold-tone bracelet designed with celestial-inspired details, featuring ornate engravings, twinkling crystals, and vibrant gemstones. This piece beautifully blends vintage charm with a modern celestial aesthetic, making it a must-have for dreamers and stargazers.",
      color: "Gold",
      sizes: ["One Size"],
      type: "Accessories",
    },
    {
      id: 27,
      name: "Floral Elegance Drop Earrings - A Blooming Beauty",
      price: 150,
      image: "ntedja/assets/acc4.jpg",
      description: "These delicate and feminine drop earrings feature an enchanting four-petal flower design with soft pastel hues, sparkling crystals, and a graceful pearl drop. A perfect blend of nature-inspired charm and elegance!",
      color: "Gold",
      sizes: ["One Size"],
      type: "Accessories",
    },
    {
      id: 28,
      name: "Vintage Denim Tote Bag",
      price: 90,
      image: "ntedja/assets/bags1.jpg",
      description: "This vintage denim tote bag combines casual style with functionality, making it a perfect everyday companion. Designed with a durable washed denim fabric, it offers a retro charm that stands out. The spacious interior provides ample room for daily essentials, while the multiple front zippered and snap-button pockets ensure easy organization. A unique corset-style lace-up detail adds a trendy touch, enhancing its fashionable appeal. With both sturdy top handles and a detachable shoulder strap, this bag offers versatile carrying options for any occasion. Whether you're heading out for a casual outing, shopping, or traveling, this stylish yet practical bag is an ideal choice for those who love denim fashion with a functional twist.",
      color: "Blue",
      sizes: ["One Size"],
      type: "Jeans",
    },
    {
      id: 29,
      name: "This pink floral-embellished shoulder bag",
      price: 95,
      image: "ntedja/assets/bags2.jpg",
      description: "This pink floral-embellished shoulder bag is a statement piece that exudes femininity and elegance. Crafted with a sleek crescent silhouette, it features intricate embroidered and beaded floral appliqués, adding a touch of romance and artistry. The delicate pink hue enhances its soft and charming appeal, making it a perfect accessory for both casual and dressy occasions. Designed with a comfortable shoulder strap and a secure closure, it balances beauty with practicality. Whether paired with a summer dress or an evening outfit, this bag effortlessly elevates any look with its unique and eye-catching floral details.",
      color: "Pink",
      sizes: ["One Size"],
      type: "Bags",
    },
    {
      id: 30,
      name: "Cream Bucket Bag",
      price: 85,
      image: "ntedja/assets/bags3.jpg",
      description: "This elegant cream-colored bucket bag is a perfect blend of sophistication and practicality. Crafted from high-quality textured leather, it features a soft yet structured silhouette that maintains its shape while allowing flexibility. The standout detail is its beautifully braided handle, adding a unique touch of style and refinement. A drawstring closure ensures security while providing a modern, relaxed feel. With its neutral tone, this bag is versatile enough to complement a variety of outfits, making it an ideal accessory for both casual outings and formal occasions.",
      color: "Cream",
      sizes: ["One Size"],
      type: "Bags",
    },
    {
      id: 31,
      name: "Heart-Shaped Handbag",
      price: 70,
      image: "ntedja/assets/bags4.jpg",
      description: "This luxurious heart-shaped handbag is a true statement piece, combining elegance with intricate craftsmanship. The deep red sequined center, featuring a keyhole design, is surrounded by ornate gold embroidery and sparkling embellishments, creating a regal and vintage-inspired aesthetic. The black leather handle, adorned with beaded accents, adds a touch of sophistication, while the gold-tone hardware and decorative key charm enhance its opulent appeal. Perfect for special occasions, this unique handbag is a stunning accessory that embodies romance, mystery, and timeless glamour.",
      color: "Black - Red",
      sizes: ["One Size"],
      type: "Bags",
    },
  ];